repos:
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
  - id: eslint
    name: TypeScript Linter
    require_serial: true
    args: [--fix, --max-warnings=0]
    files: \.(ts|mts|js|mjs)$
    types: [file]
    exclude: \.(cjs|config\.js)$
    additional_dependencies:
    - eslint@8.56.0
    - typescript@5.9.3
    - '@typescript-eslint/parser@6.7.0'
    - '@typescript-eslint/eslint-plugin@6.7.0'

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.1.0
  hooks:
  - id: prettier
    name: TypeScript/JS Formatter
    require_serial: true
    types_or: [javascript, jsx, ts, tsx, json, markdown, yaml]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    name: YAML Formatter
    require_serial: true
    args: [--autofix]
  - id: pretty-format-toml
    name: TOML Formatter
    require_serial: true
    args: [--autofix]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint
    name: Markdown Linter
    require_serial: true
    args: [--config, .markdownlintrc.json, --fix]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: check-case-conflict
